"""Add user management tables

Revision ID: 01cb66b0fa8f
Revises: d0bf2b6bda1c
Create Date: 2025-07-28 16:13:19.643684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cb66b0fa8f'
down_revision = 'd0bf2b6bda1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###