"""Add user progress and language preference tables

Revision ID: 4e861ae714fa
Revises: e91aa3c1aae4
Create Date: 2025-08-03 18:47:48.304947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e861ae714fa'
down_revision = 'e91aa3c1aae4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###