"""Add desi_stories and desi_story_vocabulary tables

Revision ID: 62be522a4031
Revises: 4e861ae714fa
Create Date: 2025-08-04 17:01:31.132715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62be522a4031'
down_revision = '4e861ae714fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desi_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.Column('english_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desi_stories_id'), 'desi_stories', ['id'], unique=False)
    
    op.create_table('desi_story_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['desi_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desi_story_vocabulary_id'), 'desi_story_vocabulary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desi_story_vocabulary_id'), table_name='desi_story_vocabulary')
    op.drop_table('desi_story_vocabulary')
    op.drop_index(op.f('ix_desi_stories_id'), table_name='desi_stories')
    op.drop_table('desi_stories')
    # ### end Alembic commands ###