"""Add user_translations table for translation history

Revision ID: b7e51e2ea33a
Revises: 84afff48834d
Create Date: 2025-08-05 16:55:17.292348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e51e2ea33a'
down_revision = '84afff48834d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###