"""Create user management system

Revision ID: d0bf2b6bda1c
Revises: 
Create Date: 2025-07-28 13:40:39.044608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bf2b6bda1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lesson_completions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'study_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_achievements', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_subscriptions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.drop_constraint(None, 'study_sessions', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'lesson_completions', type_='foreignkey')
    # ### end Alembic commands ###