"""Add CASCADE delete constraints to foreign keys

Revision ID: e91aa3c1aae4
Revises: 7a771b372585
Create Date: 2025-08-03 16:31:22.128450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91aa3c1aae4'
down_revision = '7a771b372585'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('desi_dialogue_short_story_id_fkey', 'desi_dialogue', type_='foreignkey')
    op.create_foreign_key(None, 'desi_dialogue', 'desi_short_stories', ['short_story_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lesson_completions_user_id_fkey', 'lesson_completions', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_completions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_attempts_user_id_fkey', 'quiz_attempts', type_='foreignkey')
    op.drop_constraint('quiz_attempts_quiz_question_id_fkey', 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'desi_quiz_questions', ['quiz_question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('study_sessions_user_id_fkey', 'study_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'study_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_achievements_achievement_id_fkey', 'user_achievements', type_='foreignkey')
    op.drop_constraint('user_achievements_user_id_fkey', 'user_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'user_achievements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_achievements', 'achievements', ['achievement_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_progress_user_id_fkey', 'user_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.create_foreign_key('user_progress_user_id_fkey', 'user_progress', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.create_foreign_key('user_achievements_user_id_fkey', 'user_achievements', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_achievements_achievement_id_fkey', 'user_achievements', 'achievements', ['achievement_id'], ['id'])
    op.drop_constraint(None, 'study_sessions', type_='foreignkey')
    op.create_foreign_key('study_sessions_user_id_fkey', 'study_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key('quiz_attempts_quiz_question_id_fkey', 'quiz_attempts', 'desi_quiz_questions', ['quiz_question_id'], ['id'])
    op.create_foreign_key('quiz_attempts_user_id_fkey', 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'lesson_completions', type_='foreignkey')
    op.create_foreign_key('lesson_completions_user_id_fkey', 'lesson_completions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'desi_dialogue', type_='foreignkey')
    op.create_foreign_key('desi_dialogue_short_story_id_fkey', 'desi_dialogue', 'desi_short_stories', ['short_story_id'], ['id'])
    # ### end Alembic commands ###