"""Initial Oracle schema creation

Revision ID: oracle_001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = 'oracle_001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create sequences for Oracle auto-increment
    op.execute("CREATE SEQUENCE desi_lessons_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE desi_vocabulary_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE desi_example_sentences_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE desi_short_stories_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE desi_dialogue_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE desi_quiz_questions_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE users_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE user_profiles_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE user_subscriptions_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE user_progress_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE lesson_completions_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE quiz_attempts_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE achievements_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE user_achievements_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE user_settings_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE study_sessions_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE user_translations_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE desi_stories_id_seq START WITH 1 INCREMENT BY 1")
    op.execute("CREATE SEQUENCE desi_story_vocab_id_seq START WITH 1 INCREMENT BY 1")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('points_reward', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)

    op.create_table('desi_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('target_language', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desi_lessons_id'), 'desi_lessons', ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'TEACHER', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('desi_example_sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('english', sa.Text(), nullable=False),
    sa.Column('target_language_script', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=False),
    sa.Column('pronunciation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['desi_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desi_example_sentences_id'), 'desi_example_sentences', ['id'], unique=False)

    op.create_table('desi_quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('answer', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['desi_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desi_quiz_questions_id'), 'desi_quiz_questions', ['id'], unique=False)

    op.create_table('desi_short_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['desi_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desi_short_stories_id'), 'desi_short_stories', ['id'], unique=False)

    op.create_table('desi_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('target_language', sa.String(length=100), nullable=False),
    sa.Column('cefr_level', sa.String(length=5), nullable=False),
    sa.Column('scenario', sa.String(length=500), nullable=True),
    sa.Column('english_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desi_stories_id'), 'desi_stories', ['id'], unique=False)

    op.create_table('desi_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('english', sa.String(length=200), nullable=False),
    sa.Column('target_language_script', sa.String(length=200), nullable=False),
    sa.Column('transliteration', sa.String(length=200), nullable=False),
    sa.Column('pronunciation', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['desi_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desi_vocabulary_id'), 'desi_vocabulary', ['id'], unique=False)

    op.create_table('lesson_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('sections_completed', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['desi_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_completions_id'), 'lesson_completions', ['id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('quiz_question_id', sa.Integer(), nullable=True),
    sa.Column('user_answer', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('attempt_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['desi_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['desi_quiz_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)

    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('lessons_completed', sa.Integer(), nullable=True),
    sa.Column('words_learned', sa.Integer(), nullable=True),
    sa.Column('quiz_score', sa.Float(), nullable=True),
    sa.Column('activities', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_id'), 'study_sessions', ['id'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('achievement_id', sa.Integer(), nullable=True),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('native_language', sa.String(length=100), nullable=True),
    sa.Column('learning_languages', sa.JSON(), nullable=True),
    sa.Column('primary_learning_language', sa.String(length=100), nullable=True),
    sa.Column('learning_goal', sa.String(length=100), nullable=True),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)

    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('total_lessons_completed', sa.Integer(), nullable=True),
    sa.Column('total_words_learned', sa.Integer(), nullable=True),
    sa.Column('total_quiz_score', sa.Float(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('reminder_notifications', sa.Boolean(), nullable=True),
    sa.Column('achievement_notifications', sa.Boolean(), nullable=True),
    sa.Column('audio_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_play_audio', sa.Boolean(), nullable=True),
    sa.Column('show_transliteration', sa.Boolean(), nullable=True),
    sa.Column('show_pronunciation', sa.Boolean(), nullable=True),
    sa.Column('difficulty_preference', sa.String(length=20), nullable=True),
    sa.Column('profile_public', sa.Boolean(), nullable=True),
    sa.Column('show_progress_to_friends', sa.Boolean(), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('language_display_script', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)

    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'PREMIUM', 'PRO', name='subscriptiontier'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('trial_end_date', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)

    op.create_table('user_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('from_text', sa.Text(), nullable=False),
    sa.Column('to_text', sa.Text(), nullable=False),
    sa.Column('to_text_transliteration', sa.Text(), nullable=True),
    sa.Column('from_language', sa.String(length=10), nullable=False),
    sa.Column('to_language', sa.String(length=10), nullable=False),
    sa.Column('from_language_name', sa.String(length=50), nullable=False),
    sa.Column('to_language_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_translations_id'), 'user_translations', ['id'], unique=False)

    op.create_table('desi_dialogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_story_id', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=100), nullable=False),
    sa.Column('target_language_script', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=False),
    sa.Column('english', sa.Text(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['short_story_id'], ['desi_short_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desi_dialogue_id'), 'desi_dialogue', ['id'], unique=False)

    op.create_table('desi_story_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['desi_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desi_story_vocabulary_id'), 'desi_story_vocabulary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desi_story_vocabulary_id'), table_name='desi_story_vocabulary')
    op.drop_table('desi_story_vocabulary')
    op.drop_index(op.f('ix_desi_dialogue_id'), table_name='desi_dialogue')
    op.drop_table('desi_dialogue')
    op.drop_index(op.f('ix_user_translations_id'), table_name='user_translations')
    op.drop_table('user_translations')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_study_sessions_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_lesson_completions_id'), table_name='lesson_completions')
    op.drop_table('lesson_completions')
    op.drop_index(op.f('ix_desi_vocabulary_id'), table_name='desi_vocabulary')
    op.drop_table('desi_vocabulary')
    op.drop_index(op.f('ix_desi_stories_id'), table_name='desi_stories')
    op.drop_table('desi_stories')
    op.drop_index(op.f('ix_desi_short_stories_id'), table_name='desi_short_stories')
    op.drop_table('desi_short_stories')
    op.drop_index(op.f('ix_desi_quiz_questions_id'), table_name='desi_quiz_questions')
    op.drop_table('desi_quiz_questions')
    op.drop_index(op.f('ix_desi_example_sentences_id'), table_name='desi_example_sentences')
    op.drop_table('desi_example_sentences')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_desi_lessons_id'), table_name='desi_lessons')
    op.drop_table('desi_lessons')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')

    # Drop sequences
    op.execute("DROP SEQUENCE desi_story_vocab_id_seq")
    op.execute("DROP SEQUENCE desi_stories_id_seq")
    op.execute("DROP SEQUENCE user_translations_id_seq")
    op.execute("DROP SEQUENCE study_sessions_id_seq")
    op.execute("DROP SEQUENCE user_settings_id_seq")
    op.execute("DROP SEQUENCE user_achievements_id_seq")
    op.execute("DROP SEQUENCE achievements_id_seq")
    op.execute("DROP SEQUENCE quiz_attempts_id_seq")
    op.execute("DROP SEQUENCE lesson_completions_id_seq")
    op.execute("DROP SEQUENCE user_progress_id_seq")
    op.execute("DROP SEQUENCE user_subscriptions_id_seq")
    op.execute("DROP SEQUENCE user_profiles_id_seq")
    op.execute("DROP SEQUENCE users_id_seq")
    op.execute("DROP SEQUENCE desi_quiz_questions_id_seq")
    op.execute("DROP SEQUENCE desi_dialogue_id_seq")
    op.execute("DROP SEQUENCE desi_short_stories_id_seq")
    op.execute("DROP SEQUENCE desi_example_sentences_id_seq")
    op.execute("DROP SEQUENCE desi_vocabulary_id_seq")
    op.execute("DROP SEQUENCE desi_lessons_id_seq")
    # ### end Alembic commands ###